### ISSUE TITLE
Implement  Consumer delete from Admin REST API

### ISSUE THREAD

**Issue by Asitha** [ballerina-platform/ballerina-message-broker#213]
**Description:**

Need to implement consumer deleter through the REST API.
Currently following REST resource with DELETE method returns 501 NOT IMPLEMENTED.
```
https://{{hostname}}:9000/broker/v1.0/queues/{{queueName}}/consumers/1
```

**Comment by sdkottegoda** [comment]
This is implemented through #442. It is not possible to close consumers, rather channels and connection that are assciated with the consumers.
