### ISSUE TITLE
Add Bindings view and manipulation support to CLI client

### ISSUE THREAD

**Issue by erandacr** [ballerina-platform/ballerina-message-broker#309]
**Description:**
Add the following supports to CLI client,
1. View bindings
2. Create bindings 
3. Delete bindings

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by a5anka** [comment]
Imeplementation done in https://github.com/ballerina-platform/ballerina-message-broker/pull/319
