### ISSUE TITLE
Message Broker goes OOM 

### ISSUE THREAD

**Issue by sashikamw** [ballerina-platform/ballerina-message-broker#426]
**Description:**
Message Broker goes OOM when the jms consumer is started and jms producer is publishing large (40kb) messages with average TPS of 5000 to 10000.

**Affected Product Version:**
message-broker-0.1.66

**OS, DB, other environment details and versions:**    
Ubuntu 15.10

**Steps to reproduce:**
Used the following artefacts - https://github.com/sashikamw/ballerina-stabilitytest/tree/master/ServiceScenarios/Scenario03_JMS/beta17/MultipleWorkers 

**Observations**
OOM

HeapDump - https://drive.google.com/file/d/1wEhz6X6sn5pSSsFlBHRjyNvVcthhDBf0/view?usp=sharing

**Comment by a5anka** [comment]
Fixed with #456
