### ISSUE TITLE
Test failures on Windows

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-message-broker#436]
**Description:**
Several tests seem to be failing on Windows.

Failing tests include:
1. "failed to create temp password file"
- `CipherToolTest` - `testEncryptionAndDecryption`

2. with  "configuration file path not provided" errors
- `BrokerHaConfigurationTest` - fails at setup
- `CipherToolInitializerTest` - `testExecuteTestDecryptText` and `testExecuteTestEncryptText`
- `UtilsTest` - `testCreateCipherTool`

**OS, DB, other environment details and versions:**    
Windows 

**Related Issues:**
#214

**Comment by a5anka** [comment]
@MaryamZi Can we reduce the priority since this is not critical for development and not a defect in the product distribution?

**Comment by a5anka** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-message-broker/pull/462
