### ISSUE TITLE
Refine force close operation through REST API

### ISSUE THREAD

**Issue by sdkottegoda** [ballerina-platform/ballerina-message-broker#495]
**Description:**
Refine force close operation through REST API in a way that it supports the following scenarios:
- Close connection with/without channels
- Close connection gracefully/forcefully
- Close channel with/without consumers

**Related Issues:**
https://github.com/ballerina-platform/ballerina-message-broker/issues/442

**Comment by Asitha** [comment]
This is addressed in #442
